perf(entity.get): add attribute change tracking
homebaseio/homebase-react pull request #15
Opened 2020-11-15 02:43 UTC by smothers

- improve re-render performance by ~2x on light pages
- improve re-render performance by ~4x on heavy pages with ~10k components
- only trigger re-renders on attributes that have changed
- instrument `entity.get` to track used attributes and scope them to their respective hook
- update the todo example to better leverage these new performance features
- add performance section to readme

2020-11-15 02:45 UTC, smothers commented
@rubinovitz when you get a chance to review this please also QA it locally. It touches a lot and I'd love another set of eyes on it.

2020-11-15 03:32 UTC, rubinovitz commented
@smothers Sure thing!

On Sat, Nov 14 2020 at 6:46 PM, Chris Smothers < notifications@github.com > wrote:

> 
> 
> 
> 
> 
> 
> 
> @rubinovitz ( https://github.com/rubinovitz ) when you get a chance to
> review this please also QA it locally. It touches a lot and I'd love
> another set of eyes on it.
> 
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (
> https://github.com/homebaseio/homebase-react/pull/15#issuecomment-727305970
> ) , or unsubscribe (
> https://github.com/notifications/unsubscribe-auth/AANZMF6NUU4L2QOGS3XNCRTSP46GRANCNFSM4TV5IOJA
> ).
> 
> 
>

2020-11-16 03:56 UTC, rubinovitz requested changes
@smothers I'm getting "Error: Invalid Hook" call when I try to render the Counter example now.

2020-11-16 03:56 UTC, rubinovitz commented on README.md
> +The default caching reduces unnecessary re-renders and virtual dom thrashing a lot. That said, it is still possible to trigger more re-renders than you might want.
nitpick: s/virtual dom/virtual DOM

2020-11-16 06:24 UTC, rubinovitz commented
@smothers oh standby I think this is the problem I had last time I tried to test locally and it thinks there's two Reacts. 😬 I'll do the fix I did last time and test again in the morning. You don't need to do anything.

2020-11-16 16:09 UTC, rubinovitz commented
@smothers I'm still getting the error after `npm link homebase-react/node_modules/react` , which fixed the error last time it was a double React issue. Do you get an error on your end running this version in a React js app?

2020-11-16 20:25 UTC, smothers commented
I'm getting the error if I use yarn, but npm lets me link to the local package

2020-11-16 21:13 UTC, rubinovitz approved these changes
LGTM 🏎

2020-11-16 21:52 UTC, merged